# Generated by Django 4.2.6 on 2023-11-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_post', '0002_rename_usuario_usuario_logname'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=64)),
                ('gen', models.CharField(max_length=64)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=126)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='posteo',
        ),
    ]
