# Generated by Django 4.2.6 on 2023-11-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_post', '0005_blogpost_creador_alter_blogpost_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='autor',
        ),
    ]
