# Generated by Django 4.2.6 on 2023-11-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_post', '0006_remove_blogpost_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='creador',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.DeleteModel(
            name='genero',
        ),
    ]
